export const shoes = [
  { id: 1, title: "Air Zoom Pegasus", category: "Running", brand: "Nike", price: 120.99, description: "Breathable and lightweight running shoes with responsive cushioning." },
  { id: 2, title: "Ultraboost 22", category: "Running", brand: "Adidas", price: 180.00, description: "Energy-returning running shoes for enhanced performance on every stride." },
  { id: 3, title: "Velocity Nitro", category: "Running", brand: "Puma", price: 150.50, description: "Nitro-infused foam for extra comfort and energy return." },
  { id: 4, title: "Floatride Energy", category: "Running", brand: "Reebok", price: 95.45, description: "Lightweight running shoes designed for long-distance comfort." },
  { id: 5, title: "Charged Assert 9", category: "Running", brand: "Under Armour", price: 110.00, description: "Durable and responsive running shoes with great grip." },
  { id: 6, title: "Winflo 8", category: "Running", brand: "Nike", price: 125.99, description: "A breathable, cushioned shoe designed for road running." },
  { id: 7, title: "SolarGlide 5", category: "Running", brand: "Adidas", price: 135.00, description: "Comfortable running shoes with stable support." },
  { id: 8, title: "Deviate Nitro", category: "Running", brand: "Puma", price: 165.75, description: "High-performance running shoes with carbon-infused plates." },
  { id: 9, title: "Reebok Runner 4.0", category: "Running", brand: "Reebok", price: 75.00, description: "Affordable running shoes for daily runs." },
  { id: 10, title: "HOVR Sonic 4", category: "Running", brand: "Under Armour", price: 115.00, description: "Smart running shoes with real-time performance tracking." },
  { id: 11, title: "Terrex Swift R3", category: "Hiking", brand: "Adidas", price: 165.00, description: "Durable hiking shoes with excellent traction and weather resistance." },
  { id: 12, title: "X Ultra 4", category: "Hiking", brand: "Puma", price: 185.75, description: "All-terrain hiking shoes offering stability and comfort." },
  { id: 13, title: "Hoka Speedgoat", category: "Hiking", brand: "Nike", price: 210.00, description: "High-performance hiking shoes for rugged terrains." },
  { id: 14, title: "GTX Trail Boots", category: "Hiking", brand: "Reebok", price: 190.50, description: "Trail boots built for extreme conditions and ultimate grip." },
  { id: 15, title: "Moab Speed GTX", category: "Hiking", brand: "Under Armour", price: 199.99, description: "Waterproof hiking shoes designed for all-terrain adventures." },
  { id: 16, title: "Terrex AX4", category: "Hiking", brand: "Adidas", price: 140.00, description: "Lightweight and durable hiking shoes for outdoor enthusiasts." },
  { id: 17, title: "Wildhorse 7", category: "Hiking", brand: "Nike", price: 130.00, description: "Trail-running shoes with excellent grip and durability." },
  { id: 18, title: "Drift Cat 8", category: "Hiking", brand: "Puma", price: 145.00, description: "Stylish hiking shoes for light trail adventures." },
  { id: 19, title: "Reebok Ridgerider 6", category: "Hiking", brand: "Reebok", price: 110.00, description: "Reliable trail shoes with rugged construction." },
  { id: 20, title: "UA Valsetz RTS", category: "Hiking", brand: "Under Armour", price: 135.00, description: "Tactical hiking boots built for performance." },
  { id: 21, title: "Clyde All-Pro", category: "Basketball", brand: "Puma", price: 125.00, description: "High-top basketball shoes designed for court performance and style." },
  { id: 22, title: "Harden Vol. 6", category: "Basketball", brand: "Adidas", price: 140.00, description: "Signature basketball shoes with superior cushioning for sharp movements." },
  { id: 23, title: "LeBron Witness 6", category: "Basketball", brand: "Nike", price: 160.00, description: "Durable basketball shoes with optimal ankle support and traction." },
  { id: 24, title: "Zoom Freak 3", category: "Basketball", brand: "Nike", price: 175.00, description: "Giannis Antetokounmpo's signature basketball shoes with multidirectional grip." },
  { id: 25, title: "Flow Futr X", category: "Basketball", brand: "Under Armour", price: 160.00, description: "Basketball shoes with extra stability for explosive play." },
  { id: 26, title: "Court Vision Mid", category: "Basketball", brand: "Nike", price: 130.00, description: "Classic basketball shoes with a sleek and stylish design." },
  { id: 27, title: "Fusion Nitro", category: "Basketball", brand: "Puma", price: 135.00, description: "Responsive cushioning for on-court dominance." },
  { id: 28, title: "Dame 8", category: "Basketball", brand: "Adidas", price: 150.00, description: "Signature Damian Lillard basketball shoes with sleek performance." },
  { id: 29, title: "Reebok Pump Omni Zone II", category: "Basketball", brand: "Reebok", price: 145.00, description: "Retro basketball shoes with pump technology for custom fit." },
  { id: 30, title: "HOVR Havoc 4", category: "Basketball", brand: "Under Armour", price: 155.00, description: "High-top basketball shoes for intense gameplay." },
  { id: 31, title: "Classic Slip-On", category: "Casual", brand: "Puma", price: 60.00, description: "Iconic slip-on sneakers for everyday casual wear." },
  { id: 32, title: "Stan Smith", category: "Casual", brand: "Adidas", price: 85.00, description: "Minimalist sneakers with a clean and classic look." },
  { id: 33, title: "Air Force 1", category: "Casual", brand: "Nike", price: 120.00, description: "Legendary sneakers known for their versatility and comfort." },
  { id: 34, title: "Club C 85", category: "Casual", brand: "Reebok", price: 75.00, description: "Classic sneakers with a timeless retro style." },
  { id: 35, title: "HOVR Summit Fat Tire", category: "Casual", brand: "Under Armour", price: 140.00, description: "Unique casual sneakers built for comfort and traction." },
  { id: 36, title: "Old Skool", category: "Casual", brand: "Puma", price: 75.00, description: "Low-top sneakers featuring a signature stripe and style." },
  { id: 37, title: "Gazelle", category: "Casual", brand: "Adidas", price: 70.00, description: "Classic suede sneakers with a timeless look." },
  { id: 38, title: "Blazer Mid '77", category: "Casual", brand: "Nike", price: 110.00, description: "Retro-inspired casual sneakers with bold style." },
  { id: 39, title: "Reebok NPC II", category: "Casual", brand: "Reebok", price: 65.00, description: "Minimalist sneakers with a low-cut design for mobility." },
  { id: 40, title: "UA Spawn 4", category: "Casual", brand: "Under Armour", price: 95.00, description: "Stylish low-profile sneakers for casual use." },
  { id: 41, title: "Nano X1", category: "Training", brand: "Reebok", price: 130.00, description: "Versatile training shoes built for all workout intensities." },
  { id: 42, title: "Metcon 7", category: "Training", brand: "Nike", price: 140.00, description: "Sturdy training shoes with exceptional grip and stability." },
  { id: 43, title: "Project Rock 4", category: "Training", brand: "Under Armour", price: 155.00, description: "Signature training shoes for hardcore workouts." },
  { id: 44, title: "Puremotion Adapt", category: "Training", brand: "Adidas", price: 95.00, description: "Flexible training shoes with a sock-like fit." },
  { id: 45, title: "Fuse TR", category: "Training", brand: "Puma", price: 115.00, description: "Training shoes designed for maximum durability." },
  { id: 46, title: "UA Tribase Reign 4", category: "Training", brand: "Under Armour", price: 145.00, description: "Engineered for ultimate ground contact and stability." },
  { id: 47, title: "Free Metcon 4", category: "Training", brand: "Nike", price: 135.00, description: "Flexible yet supportive training shoes for high-intensity workouts." },
  { id: 48, title: "Adipower Weightlifting 2", category: "Training", brand: "Adidas", price: 225.00, description: "High-stability training shoes for weightlifting and performance." },
  { id: 49, title: "Sole Fury Adapt", category: "Training", brand: "Reebok", price: 115.00, description: "Innovative training shoes for both style and functionality." },
  { id: 50, title: "Axelion", category: "Training", brand: "Puma", price: 125.00, description: "Modern training shoes built for versatility and support." },
];